import type { TargetWriteClient } from '../../core/types.js';
import type {
  ArchivePullRequestsPayload,
  MigrationPullRequest,
} from './types.js';

export interface PrArchiveResult {
  readonly success: boolean;
  readonly archiveIssueNumber?: number | undefined;
  readonly error?: string | undefined;
}

export function generateHistoricalPrMarkdown(
  closedPrs: readonly MigrationPullRequest[],
): string {
  const lines: string[] = [
    '# Historical Pull Requests Archive',
    '',
    'This archive records historical pull requests from the source repository that were closed or merged prior to migration.',
    '',
    '| # | Title | State | Author | Base <- Head | Merged / Closed At |',
    '|---|---|---|---|---|---|',
  ];

  for (const pr of closedPrs) {
    const status = pr.merged ? 'Merged' : 'Closed';
    const date = pr.mergedAt ?? pr.closedAt ?? pr.createdAt;
    const author = pr.author ? `@${pr.author}` : 'unknown';
    // Escape pipes in title
    const safeTitle = pr.title.replace(/\|/g, '\\|');
    lines.push(
      `| #${pr.number} | ${safeTitle} | ${status} | ${author} | \`${pr.baseRef}\` <- \`${pr.headRef}\` | ${date} |`,
    );
  }

  lines.push('');
  lines.push('---');
  lines.push('*Automated archival record generated by GHEC Consultant Suite.*');

  return lines.join('\n');
}

export async function archiveClosedPullRequests(
  targetWriteClient: TargetWriteClient,
  targetOrg: string,
  targetRepo: string,
  payload: ArchivePullRequestsPayload,
  signal: AbortSignal,
  dryRun: boolean,
): Promise<PrArchiveResult> {
  if (dryRun) {
    return { success: true };
  }

  const body = generateHistoricalPrMarkdown(payload.closedPrs);

  try {
    const res = await targetWriteClient.mutate<{ number: number }>(
      {
        id: 'rest.issues.createArchiveIssue',
        method: 'POST',
        path: '/repos/{owner}/{repo}/issues',
        pathParams: { owner: targetOrg, repo: targetRepo },
        body: {
          title: payload.archiveTitle,
          body,
          labels: ['migration-archive', 'pull-requests'],
        },
      },
      signal,
    );

    if (res.status < 200 || res.status >= 300 || !res.data?.number) {
      return {
        success: false,
        error: `Failed to create archive issue: HTTP ${res.status}`,
      };
    }

    const issueNumber = res.data.number;

    // Immediately close the archive issue so it remains as a closed audit record
    try {
      await targetWriteClient.mutate(
        {
          id: 'rest.issues.closeArchiveIssue',
          method: 'PATCH',
          path: '/repos/{owner}/{repo}/issues/{issue_number}',
          pathParams: {
            owner: targetOrg,
            repo: targetRepo,
            issue_number: String(issueNumber),
          },
          body: { state: 'closed' },
        },
        signal,
      );
    } catch {
      // Issue is created; closing is non-fatal
    }

    return {
      success: true,
      archiveIssueNumber: issueNumber,
    };
  } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : String(err);
    return {
      success: false,
      error: `Historical PR archive creation failed: ${msg}`,
    };
  }
}
