import type { MannequinRecord } from './types.js';

/**
 * Parses CSV lines considering quotes and commas compliant with RFC 4180.
 */
function parseCsvLine(line: string): string[] {
  const result: string[] = [];
  let current = '';
  let inQuotes = false;
  let i = 0;

  while (i < line.length) {
    const char = line[i];

    if (inQuotes) {
      if (char === '"') {
        if (i + 1 < line.length && line[i + 1] === '"') {
          current += '"';
          i += 2;
          continue;
        } else {
          inQuotes = false;
        }
      } else {
        current += char;
      }
    } else {
      if (char === '"') {
        inQuotes = true;
      } else if (char === ',') {
        result.push(current.trim());
        current = '';
      } else {
        current += char;
      }
    }
    i++;
  }

  result.push(current.trim());
  return result;
}

/**
 * Escapes a single cell value for standard CSV output.
 */
function escapeCsvCell(value: string | undefined): string {
  if (value === undefined || value === null) {
    return '';
  }
  const str = String(value).trim();
  if (
    str.includes(',') ||
    str.includes('"') ||
    str.includes('\n') ||
    str.includes('\r')
  ) {
    return `"${str.replaceAll('"', '""')}"`;
  }
  return str;
}

/**
 * Parses raw CSV output generated by `gh gei generate-mannequin-csv`.
 *
 * Expected headers:
 * `mannequin-user,mannequin-id,target-user`
 */
export function parseMannequinCsv(csvContent: string): MannequinRecord[] {
  if (!csvContent || !csvContent.trim()) {
    return [];
  }

  const lines = csvContent
    .split(/\r?\n/)
    .map((l) => l.trim())
    .filter((l) => l.length > 0);

  if (lines.length === 0) {
    return [];
  }

  // Find header index
  const headerLine = lines[0]!;
  const headers = parseCsvLine(headerLine).map((h) => h.toLowerCase());

  const mannequinUserIdx = headers.findIndex(
    (h) => h === 'mannequin-user' || h === 'mannequin_user',
  );
  const mannequinIdIdx = headers.findIndex(
    (h) => h === 'mannequin-id' || h === 'mannequin_id' || h === 'id',
  );
  const targetUserIdx = headers.findIndex(
    (h) => h === 'target-user' || h === 'target_user',
  );

  if (mannequinUserIdx === -1 || mannequinIdIdx === -1) {
    throw new Error(
      `Invalid mannequin CSV header: required 'mannequin-user' and 'mannequin-id', found [${headers.join(', ')}]`,
    );
  }

  const records: MannequinRecord[] = [];

  for (let i = 1; i < lines.length; i++) {
    const rawLine = lines[i]!;
    const fields = parseCsvLine(rawLine);

    const mannequinUser = fields[mannequinUserIdx] ?? '';
    const mannequinId = fields[mannequinIdIdx] ?? '';
    const targetUser =
      targetUserIdx !== -1 ? (fields[targetUserIdx] ?? '') : '';

    if (!mannequinUser && !mannequinId) {
      continue;
    }

    records.push({
      mannequinUser,
      mannequinId,
      ...(targetUser ? { targetUser } : {}),
      status: targetUser ? 'completed' : 'pending',
    });
  }

  return records;
}

/**
 * Serializes an array of MannequinRecord objects into RFC 4180 compliant CSV string
 * suitable for `gh gei reclaim-mannequin --csv <path>`.
 */
export function serializeMannequinCsv(
  records: readonly MannequinRecord[],
): string {
  const header = 'mannequin-user,mannequin-id,target-user';
  const rows = records.map((r) => {
    return [
      escapeCsvCell(r.mannequinUser),
      escapeCsvCell(r.mannequinId),
      escapeCsvCell(r.targetUser ?? ''),
    ].join(',');
  });

  return [header, ...rows].join('\n');
}
